compiler:
	flex myscanner.l
	g++ lex.yy.cc -ll -o compiler
clean:
	rm lex.yy.cc
	rm compiler
team:
	@echo "Team: Kims' Club"
	@echo
	@echo "Sang Hun Kim"
	@echo "dooly107"
	@echo
	@echo "Jeong Min (Jimmy) Kim"
	@echo "jeongjimmykim"
